/**
 * Last name: Jatyani
 * First name: Armeet
 * Period: 2
 * 
 * In this lab you will practice inheritance You will need
 * to use System.out.println (String) to print messages to the console.
 * 
 * Write a driver class to test the methods of the Shape class and it's sub classes
 * Do the following:
 * 1. Create a Shape object called "Irregular shape". Call it myShape.
 * 2. Print myShape's name.
 * 3. Create a Rectangle object called "Rectangle". Call it myRect.
 * 4. Print myRect's name.
 * 5. Print myRect's message.
 * 6. Create a Square object. Call it mySqr.
 * 7. Print mySqr's name.
 * 8. Print mySqr's message.
 * 9. Create a Circle object. Call it myCircle.
 * 7. Print myCircle's name.
 * 8. Print myCircle's message.
 * 
 * After you have filled in the instructions, copy and paste the program into Code Check.
 * The link is provided on canvas. Once you get the program to pass, download the
 * zipped file generated by Code Check. DO NOT open or unzip this file. Submit the zipped file 
 * on Canvas. 
 */

public class ShapesDriver {

    public static void main(String[] args) {
        //Your code goes here

        // init myShape
        Shape myShape = new Shape("Irregular shape");
        // use printName method to print this shape's name
        myShape.printName();

        // create myRect
        Rectangle myRect = new Rectangle();
        myRect.printName();
        myRect.printMessage();

        // create mySqr
        Square mySqr = new Square();
        mySqr.printName();
        mySqr.printMessage();

        // create myCircle
        Circle myCircle = new Circle();
        myCircle.printName();
        myCircle.printMessage();
    }

}
